
* Suggestions

`arubi` from #bitcoin-dev

    10:44 <arubi> jb55, awesome. for my serializer, I also defined a few "make
    your life easy" templates, like plain numbers are treated as scriptnum (need
    to be valid), the character @ means minimal push, so something like @<hex
    pubkey> is converted to 0x21 0x<pubkey> (and longer pushes if needed), a
    0x<hex> is just treated like literal serialized part of the script.. you're
    probably already on it, but just my pov :)
    
    11:16 <arubi> the behavior is pretty similar really, segwit serializes the
    codesep while legacy doesn't. segwit makes checksig ops a lot easier because
    of the better sighash scheme in bip143. there are so many interesting
    sighash types, and there are probably going to be more eventually, that
    implementing legacy just seems like a waste of time now

* Evaluator

Some things to consider

- [ ] May need context for things like CSV
- [ ] Should we represent context as the program environment?
- [ ] Pure environment and perhaps live testnet environment?
- [ ] How to do this?
